# ----
# Site

title: RxJS Quickstart
description: A template for OneHungryMind endeavours.
url: https://example.com
google_analytics_key:
permalink: pretty

collections:
  basics:
    title: Basics
    position: 1
  state:
    title: State
    position: 2
  realtime:
    title: Realtime
    position: 3

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - github-pages

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
